language: php

jobs:
  include:
    - php: "5.4"
    - php: "5.5"
    - php: "5.6"
    - php: "7.0"
    - php: "7.1"
    - php: "7.2"
    - php: "7.3"
    - php: "hhvm"
    - php: "7.1"
      arch: ppc64le
    - php: "7.2"
      arch: ppc64le
  allow_failures:
    - php: hhvm

dist: trusty

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "session.serialize_handler = php" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
  - composer install --dev --prefer-source
